# Generated by Django 5.0.1 on 2024-02-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_brand_alter_car_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ImageField(default=1, upload_to='cars/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='plate',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
